Hot-Foaming Process

In [29]:
import numpy as np
def genBN(nT,mu4,mu5,sigma):
    X4 = np.random.randn(nT)*sigma + mu4
    X5 = np.random.randn(nT)*sigma + mu5
    X2 = 0.325*X5 + 0.493*X4
    X3 = 0.688*X4
    X1 = 0.574*X2 + 0.335*X3
    return np.c_[X1,X2,X3,X4,X5]

def getmu(mu4,mu5):
    X4 = mu4
    X5 = mu5
    X2 = 0.325*X5 + 0.493*X4
    X3 = 0.688*X4
    X1 = 0.574*X2 + 0.335*X3
    return np.c_[X1,X2,X3,X4,X5]

In [31]:
M = np.c_[getmu(0,1).T, getmu(1,0).T]

array([[0.18655 , 0.513462],
       [0.325   , 0.493   ],
       [0.      , 0.688   ],
       [0.      , 1.      ],
       [1.      , 0.      ]])

In [44]:
sigma = 1
delta = 1

def data_gen_func0(n_batch, Tmax, seed):
    mu4 = 0
    mu5 = 0
    np.random.seed(seed)    
    p = 5
    data = np.zeros(n_batch, Tmax, p)
    for i in range(n_batch):
        data[i] = genBN(Tmax,mu4,mu5,sigma)
    return data

def data_gen_func1(n_batch, Tmax, seed, T0, delta,mode):
    if mode == 1:
        mu4 = 1
        mu5 = 0
    else:
        mu4 = 0
        mu5 = 1
    np.random.seed(seed)
    for i in range(n_batch):
        data[i,:T0,:] = genBN(T0,mu4,mu5,sigma)
        data[i,T0:,:] = genBN(Tmax-T0,mu4,mu5,sigma)
    return data


array([[0.18655   , 0.34547625],
       [0.325     , 0.493     ],
       [0.        , 0.688     ],
       [0.        , 1.        ],
       [1.        , 0.        ]])

array([ 0.92499149, -0.75128289,  0.11097787, -0.71485655,  0.13732513])